# Generated by Django 5.0.1 on 2024-01-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeattendance',
            name='week',
        ),
    ]
