# Generated by Django 5.0.1 on 2024-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeattendance',
            name='unitAttendent',
            field=models.JSONField(),
        ),
    ]
