# Generated by Django 4.2.6 on 2023-10-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='units',
            new_name='selected_units',
        ),
    ]
