# Generated by Django 4.2.6 on 2023-10-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_units_student_selected_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='selected_units',
            new_name='units',
        ),
    ]
